#eureka:
#  instance:
#    hostname: localhost #指定主机地址
#  client:
#    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
#    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      defaultZone: http://replica2:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true