eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://replica2:8002/eureka/,http://replica1:8001/eureka/ #配置注册中心地址
spring:
  application:
    name: shop-gateway
server:
  port: 9000

#配置微服务名字的别名
zuul:
  routes:
    shop-cate-api: #微服务的名字 spring.application.name
      path: /cate/** #对应访问的路径
    shop-goods-api:
      path: /goods/**
    shop-member-api:
      path: /member/**
    shop-cart-api:
      path: /cart/**

fh:
  shop:
    member:
      checkUrls:
        /api/members/logout,/api/members/findMember,/api/carts/findCartCount,/api/carts/deleteCart,/api/carts/deleteBatchCart,/api/carts/findCart,/api/carts/addCartItem


